### ISSUE TITLE
Output to png ?

### ISSUE THREAD

**Issue by stuaxo** [zectorio/mesh-gradient-js#2]
If this could output to png it should make it easy to check against reference renders (e.g. by Cairo + future web browsers)

**Comment by jay3sh** [comment]
Outside scope of this project.
librsvg2 has tools to convert SVGs to PNGs (however this polyfill won't help in that conversion)
One way to render PNG of the SVG running this polyfill is to load it in browser and print it from there. A separate JS library could be written to render such SVG on a html5 canvas and then save it as PNG/JPEG. But it doesn't belong to this project.
