### ISSUE TITLE
Use GitHub Pages to display samples 

### ISSUE THREAD

**Issue by AmeliaBR** [zectorio/mesh-gradient-js#3]
To make [the sample files](https://github.com/zectorio/mesh-gradient-js/tree/master/samples) viewable online, you could enable [GitHub pages](https://help.github.com/articles/what-is-github-pages/), creating a simple index.html file that links to the samples with and without polyfill.

**Comment by jay3sh** [comment]
Done. You can view them at https://zectorio.github.io/mesh-gradient-js/
