### ISSUE TITLE
Use patterns to replace the meshgradient as an SVG paint server

### ISSUE THREAD

**Issue by AmeliaBR** [zectorio/mesh-gradient-js#5]
To keep the generated DOM & styles as close as possible to the original, I would recommend putting the generated `<image>` inside a `<pattern>`, and using the `<pattern>` to paint the shape that should be painted with the `<meshGradient>`.    

If you reuse the same id value from the meshGradient, then you shouldn't need to worry about parsing CSS on the shapes, you would just look for the actual <meshGradient> objects.  The shapes would still be painted by the paint server with `id="meshGradientXXX"`, it's just that that id would now be on a `<pattern>` element.

So code like this:

```svg
  <defs>
    <meshGradient
       id="meshGradient5889"
       x="300" y="100"
       gradientUnits="userSpaceOnUse">
...
    </meshGradient>
  </defs>
  <rect
     style="fill:url(#meshGradient5889);fill-opacity:1"
     id="rect11482"
     width="200" height="200" x="300"y="100" />
```

would end up looking like this:

```svg
  <defs>
    <pattern
       id="meshGradient5889"
       x="300" y="100" width="200" height="200"
       gradientUnits="userSpaceOnUse">
      <image xlink:href="data:..." width="200" height="200" />
    </pattern>
  </defs>
  <rect
     style="fill:url(#meshGradient5889);fill-opacity:1"
     id="rect11482"
     width="200" height="200" x="300"y="100" />
```

**Advantages**:

- Works with any way of applying fill styles (`style` attribute, `fill` attribute, or CSS)
- Works with mesh gradients on strokes
- Works even with dynamic CSS (such as a `:hover` style that switches a shape to a different gradient) or with dynamic shapes (e.g., an animated circle that changes radius)

**Disadvantages**:

- You would need to calculate the `width` and `height` of the gradient image based on the partial paths in the gradient `<stop>` element.
- For `objectBoundingBox` gradients, you would need to guess at the maximum resolution that might be required.  (But Inkscape isn't generating this type of gradient yet, so this is less of an issue for now.) 
- To also support a `<mesh>`, you would need to generate a `<path>` and then add a `style` attribute to paint it with the `<pattern>`.  But that is a separate issue, and is also less urgent, because I don't think Inkscape is creating standalone `<mesh>` elements yet.

**Comment by jay3sh** [comment]
This is great idea. I think it will also allow me to remove my half-baked clipping code on the image. I'll give it a try.

**Comment by jay3sh** [comment]
I did a quick change to use patterns. It's in this branch https://github.com/zectorio/mesh-gradient-js/tree/pattern

The rendering works, but I see some blurring at the edges. This is how sample1.svg looks like
![pattern-blurs](https://cloud.githubusercontent.com/assets/687977/22123565/1ecda37c-de5a-11e6-91fa-c13f78a9272c.png)

I don't know if there's something with the way patterns are rendered or something I can change.

You can try it by switching to `pattern` branch and execute 

    npm run addpolyfill docs/samples/sample1.svg dev

**Comment by AmeliaBR** [comment]
Ah, this was my fault.  I forget to mention that you needed to replace the `gradientUnits="userSpaceOnUse"` attribute with a `patternUnits="userSpaceOnUse"` attribute.  Otherwise, the width & height of the pattern tile is set as 200*the rectangle width (aka, HUGE), and the browser compensates by making the pattern really low resolution (see [this discussion of the same issue with blurry patterns](https://twitter.com/yoksel_en/status/794209979016343552)).  

(PS, The reason why the gradient is still the correct size, even though its the wrong resolution, is because the `patternContentUnits`, which determine the dimensions of the `<image>` are `userSpaceOnUse` by default.)

That should probably fix this problem. I'll take a closer look at your branch when I get a chance.

**Comment by jay3sh** [comment]
I set the `patternUnits`. I think it should do the trick, but I'm getting very weird result with it. I tried plaing with `width` and `height` attributes of both pattern and image tags. But I can't make sense out of these results.

![weird-pattern1](https://cloud.githubusercontent.com/assets/687977/22153084/c41ef79c-def3-11e6-8e9a-53a3a752521c.png)

![pattern-weird-2](https://cloud.githubusercontent.com/assets/687977/22153023/78b9ae5a-def3-11e6-8a05-6b6a924d19ac.png)

![weird-patter-3](https://cloud.githubusercontent.com/assets/687977/22153117/eb002f20-def3-11e6-81f4-f84b2c6b4199.png)

**Comment by AmeliaBR** [comment]
OK, I really should have tested out code before writing it here.  It's so easy to forget details when they are all theoretical.

The issue is that with `userSpaceOnUse` patterns, the patterns are being tiled relative to the coordinate system origin, instead of the box being filled. So the tiles don't line up correctly with the shape.  

To position the tile in the correct place, you also need the `x` and `y` attributes on the `<pattern>`, which you could calculate for now in the same way as you were calculating `x` and `y` for the absolutely-positioned `<image>`.   Ideally, you would calculate the combined path for all the mesh gradient patches, and use the bounding box of that to set `x`, `y`, `width`, and `height` on the `<pattern>`.

**Comment by jay3sh** [comment]
That was it. Thanks @AmeliaBR
